### ISSUE TITLE
Settings for left-sidebar location

### ISSUE THREAD

**Issue by ariccb** [Redundakitties/colorful-minimalist#2]
I like your settings and would love to use them, however my brain can't handle a right-side location for the sidebar. I need it on the left side. Any idea what settings I would change to get that working for me?

**Comment by Redundakitties** [comment]
Yes! I just added a file option for that, let me know if that works for you. 👍

**Comment by Redundakitties** [comment]
I will close this now, but feel free to re-open if there's anything you find I haven't addressed!
