### ISSUE TITLE
make sidebar background match adaptative tab bar color

### ISSUE THREAD

**Issue by vlebert** [Redundakitties/colorful-minimalist#3]
Hi

Thanks for your tweaks, great job. I have a question: I dont manage to make sidebery tab bar color match adaptative color from 
https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-color/

How did you get it ?

**Comment by Redundakitties** [comment]
try these settings: (found under appearance) 
![image](https://user-images.githubusercontent.com/38409600/216063868-780d17a3-ff2b-4465-a0d6-940ef15e2289.png)

and this one (found under styles editor)
![image](https://user-images.githubusercontent.com/38409600/216064080-70f9da24-49c9-4715-85fc-7ac069727d62.png)

**Comment by vlebert** [comment]
Thanks,

Well I guess our version differ because I don't have these options :

Could it be related to this message :

> Notes:
> - To apply theme color to Sidebery buttons in browser interface set "svg.context-properties.content.enabled" to "true" in about:config page.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/49779177/216064931-563bb14f-7f18-4778-aa40-1b0063e92a6d.png">

<img width="905" alt="image" src="https://user-images.githubusercontent.com/49779177/216065123-b87ec9ac-4fbd-4d27-b211-b74b83f0fcc0.png">

**Comment by Redundakitties** [comment]
What version of sidebery are you on? This repo uses [Sidebery beta v5](https://github.com/mbnuqw/sidebery/releases), though I plan to update to v6 soon

**Comment by vlebert** [comment]
upgrading to beta immediatly fixed my issue
