### ISSUE TITLE
Don't collapse when dragging tabs

### ISSUE THREAD

**Issue by emiham** [Redundakitties/colorful-minimalist#9]
When trying to drag a tab, the sidebar will immediately collapse. I think it would make sense to keep it expanded.

**Comment by Redundakitties** [comment]
Hm.... Can you tell me more about which css file you're using to autohide and which version of sidebery you're on? I don't see this behavior on my own machine for any of the autohide files I have in this repo. Are you updated to the most recent version of firefox and are you using sidebery beta v5?

**Comment by Redundakitties** [comment]
please reopen when you have more information about recreating this bug? ty

**Comment by Ashbd9** [comment]
I seem to be having this issue as well. I am on linux, and using firefox developer edition version 118.0b5 and sidebery 5.0.0rc4 (latest).
I directly copied userChrome.css and the hacks file from this repository into my profile chrome folder without any modifications.
What do you think could be causing this problem?

Thanks in advance.

**Comment by Ashbd9** [comment]
I am using the sideberyMODS.css file (default).

**Comment by Ashbd9** [comment]
I created a new firefox profile and tested it over there as well, but the sidebar closes when trying to drag a tab. So other addons could not be causing this behaviour.

**Comment by Ashbd9** [comment]
Alright I tested it on another computer that has Windows 10 on it and it works there. The sidebar does not collapse when you start dragging the tabs in Windows 10, but it does in Linux. I guess OP is also using Linux.

**Comment by Ashbd9** [comment]
Not realy a bummer, since I can use sidebery keyboard shortcuts to move tabs left and right, and to another panel especially the latter.
Anyways I like the CSS. Thanks for your work!

**Comment by emiham** [comment]
Sorry for disappearing, I had a hard time making sense of this bug as well. @Ashbd9 is right, I am also using Linux, so it seems to be a Linux specific issue in either Sidebery or Firefox. I'll close this since the problem is not with this CSS.

**Comment by emiham** [comment]
After doing some more research, here is the relevant Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1818517

There is a fix in that thread: setting `widget.gtk.ignore-bogus-leave-notify` to `1` in `about:config` seems to solve it, but no guarantees on what else that affects.
